import java.io.*;
import java.awt.Color;
import java.applet.*;
import java.awt.Cursor;
import java.net.URL;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * NewJFrame.java
 *
 * Created on Jan 2, 2013, 11:26:51 PM
 */
/**
 *
 * @author DARSHITA
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        Signin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LoginTF = new javax.swing.JTextField();
        Pwdpf = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Sel = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        BirthLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        msg = new javax.swing.JDialog();
        Alr = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        About = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        birthdayevent = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PlatDetail = new javax.swing.JButton();
        GoldDetail = new javax.swing.JButton();
        SilDetail = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CustPack = new javax.swing.JButton();
        CheckSTS = new javax.swing.JButton();
        pl = new javax.swing.JLabel();
        gol = new javax.swing.JLabel();
        sil = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Date = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        DateBTN = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        platinum = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        silver = new javax.swing.JDialog();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        gold = new javax.swing.JDialog();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        Custom = new javax.swing.JFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Charge = new javax.swing.JButton();
        ac = new javax.swing.JCheckBox();
        m = new javax.swing.JCheckBox();
        d = new javax.swing.JCheckBox();
        food = new javax.swing.JComboBox();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        cd = new javax.swing.JRadioButton();
        charge = new javax.swing.JLabel();
        caop = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        CustReg = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Form = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        fon = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        bpn = new javax.swing.JTextField();
        tc = new javax.swing.JLabel();
        adc = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();
        packe = new javax.swing.JLabel();
        RegBTN = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        CanEvnt = new javax.swing.JButton();
        dat = new javax.swing.JLabel();
        noope = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        checkSTS = new javax.swing.JFrame();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Next = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Welcome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        Wel = new javax.swing.JLabel();

        id.setTitle("Login Id");
        id.setMinimumSize(new java.awt.Dimension(625, 480));
        id.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                idWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show_production_event_management.jpg"))); // NOI18N

        Signin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Signin.setMnemonic(KeyEvent.VK_S);
        Signin.setText("Sign In");
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel7.setText("Username:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel8.setText("Password:");

        LoginTF.setFont(new java.awt.Font("Tahoma", 0, 18));

        Pwdpf.setFont(new java.awt.Font("Tahoma", 0, 18));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenu1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("ABOUT");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        id.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout idLayout = new javax.swing.GroupLayout(id.getContentPane());
        id.getContentPane().setLayout(idLayout);
        idLayout.setHorizontalGroup(
            idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addGroup(idLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pwdpf, 0, 0, Short.MAX_VALUE)
                    .addComponent(LoginTF, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        idLayout.setVerticalGroup(
            idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Pwdpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(idLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        Sel.setTitle("Event Selection");
        Sel.setMinimumSize(new java.awt.Dimension(630, 420));
        Sel.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SelWindowActivated(evt);
            }
        });
        Sel.getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 30));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Event Selection");
        Sel.getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 20, 250, 50);

        BirthLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36));
        BirthLabel.setForeground(new java.awt.Color(255, 0, 204));
        BirthLabel.setText("BIRTHDAY");
        BirthLabel.setToolTipText("Click to select the birthday event");
        BirthLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BirthLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BirthLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BirthLabelMouseExited(evt);
            }
        });
        Sel.getContentPane().add(BirthLabel);
        BirthLabel.setBounds(240, 220, 250, 40);

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 44));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Free-Animated-Wallpaper.jpg"))); // NOI18N
        jLabel9.setText("BIRTHDAY");
        Sel.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 620, 430);

        msg.setTitle("Alert");
        msg.setMinimumSize(new java.awt.Dimension(340, 160));
        msg.setResizable(false);
        msg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                msgWindowActivated(evt);
            }
        });

        Alr.setFont(new java.awt.Font("Tahoma", 0, 24));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout msgLayout = new javax.swing.GroupLayout(msg.getContentPane());
        msg.getContentPane().setLayout(msgLayout);
        msgLayout.setHorizontalGroup(
            msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alr, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        msgLayout.setVerticalGroup(
            msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        About.setTitle("About");
        About.setMinimumSize(new java.awt.Dimension(465, 250));
        About.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                AboutWindowActivated(evt);
            }
        });
        About.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 27));
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setText("Event Management System");
        About.getContentPane().add(jLabel12);
        jLabel12.setBounds(150, 10, 290, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Version: 1.0");
        About.getContentPane().add(jLabel13);
        jLabel13.setBounds(220, 70, 110, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Vendor: Chirag Garg");
        About.getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 100, 161, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Copyright: 2013");
        About.getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 130, 128, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 16));
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Visit us: chiragjavaprogrammer.com");
        About.getContentPane().add(jLabel16);
        jLabel16.setBounds(161, 170, 260, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector-flower-patterns-background-60_1920x1200_70571.jpg"))); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(470, 280));
        jLabel11.setMinimumSize(new java.awt.Dimension(470, 280));
        About.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 450, 210);

        birthdayevent.setTitle("Birthday Event");
        birthdayevent.setMinimumSize(new java.awt.Dimension(680, 510));
        birthdayevent.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                birthdayeventWindowActivated(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/happy_birthday_cake-12419.gif"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Brush Script MT", 0, 27));
        jLabel18.setForeground(new java.awt.Color(204, 0, 204));
        jLabel18.setText("Birthday Packages");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel19.setForeground(new java.awt.Color(204, 0, 204));
        jLabel19.setText("Customization of Packages");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel20.setForeground(new java.awt.Color(153, 0, 153));
        jLabel20.setText("Check Status");

        PlatDetail.setFont(new java.awt.Font("Tahoma", 0, 14));
        PlatDetail.setForeground(new java.awt.Color(255, 0, 204));
        PlatDetail.setText("Details");
        PlatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatDetailActionPerformed(evt);
            }
        });

        GoldDetail.setFont(new java.awt.Font("Tahoma", 0, 14));
        GoldDetail.setForeground(new java.awt.Color(255, 0, 204));
        GoldDetail.setText("Details");
        GoldDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldDetailActionPerformed(evt);
            }
        });

        SilDetail.setFont(new java.awt.Font("Tahoma", 0, 14));
        SilDetail.setForeground(new java.awt.Color(255, 0, 204));
        SilDetail.setText("Details");
        SilDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilDetailActionPerformed(evt);
            }
        });

        CustPack.setFont(new java.awt.Font("Tahoma", 0, 14));
        CustPack.setForeground(new java.awt.Color(255, 51, 204));
        CustPack.setText("Customize Package");
        CustPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustPackActionPerformed(evt);
            }
        });

        CheckSTS.setFont(new java.awt.Font("Tahoma", 0, 14));
        CheckSTS.setForeground(new java.awt.Color(255, 0, 204));
        CheckSTS.setText("ENTER");
        CheckSTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSTSActionPerformed(evt);
            }
        });

        pl.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18));
        pl.setForeground(new java.awt.Color(204, 0, 204));
        pl.setText("Platinum");
        pl.setToolTipText("Click to get the package");
        pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plMouseExited(evt);
            }
        });

        gol.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18));
        gol.setForeground(new java.awt.Color(204, 0, 204));
        gol.setText("Gold");
        gol.setToolTipText("Click to get the package");
        gol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                golMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                golMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                golMouseExited(evt);
            }
        });

        sil.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18));
        sil.setForeground(new java.awt.Color(204, 0, 204));
        sil.setText("Silver");
        sil.setToolTipText("Click to get the package");
        sil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                silMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                silMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                silMouseExited(evt);
            }
        });

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Events");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Sign out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Back");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar2.add(jMenu4);

        birthdayevent.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout birthdayeventLayout = new javax.swing.GroupLayout(birthdayevent.getContentPane());
        birthdayevent.getContentPane().setLayout(birthdayeventLayout);
        birthdayeventLayout.setHorizontalGroup(
            birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayeventLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(birthdayeventLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(birthdayeventLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, birthdayeventLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pl)
                                        .addComponent(sil)
                                        .addComponent(gol))
                                    .addGap(26, 26, 26)
                                    .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PlatDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SilDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GoldDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(birthdayeventLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(CustPack, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(birthdayeventLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(CheckSTS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        birthdayeventLayout.setVerticalGroup(
            birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayeventLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pl)
                    .addComponent(PlatDetail))
                .addGap(15, 15, 15)
                .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoldDetail)
                    .addComponent(gol))
                .addGap(18, 18, 18)
                .addGroup(birthdayeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sil)
                    .addComponent(SilDetail))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(CustPack)
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckSTS)
                .addGap(40, 40, 40))
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        Date.setTitle("Select Date");
        Date.setMinimumSize(new java.awt.Dimension(490, 310));
        Date.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                DateWindowActivated(evt);
            }
        });
        Date.getContentPane().setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Select Date:");
        Date.getContentPane().add(jLabel21);
        jLabel21.setBounds(80, 100, 140, 30);

        DateBTN.setFont(new java.awt.Font("Tahoma", 0, 24));
        DateBTN.setForeground(new java.awt.Color(0, 0, 204));
        DateBTN.setText("Enter");
        DateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateBTNActionPerformed(evt);
            }
        });
        Date.getContentPane().add(DateBTN);
        DateBTN.setBounds(170, 200, 100, 30);

        jDateChooser1.setForeground(new java.awt.Color(0, 0, 204));
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18));
        Date.getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(220, 100, 140, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (13).jpg"))); // NOI18N
        Date.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 490, 310);

        platinum.setTitle("Platinum Package");
        platinum.setMinimumSize(new java.awt.Dimension(530, 330));
        platinum.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                platinumWindowActivated(evt);
            }
        });
        platinum.getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel23.setForeground(new java.awt.Color(255, 0, 255));
        jLabel23.setText("Platinum Package Information");
        platinum.getContentPane().add(jLabel23);
        jLabel23.setBounds(60, 20, 400, 41);
        platinum.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 0, 0);

        jLabel48.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel48.setForeground(new java.awt.Color(0, 0, 255));
        jLabel48.setText("1. Airconditioned           ");
        platinum.getContentPane().add(jLabel48);
        jLabel48.setBounds(30, 80, 210, 28);

        jLabel49.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("2. Music Night DJ");
        platinum.getContentPane().add(jLabel49);
        jLabel49.setBounds(30, 110, 200, 30);

        jLabel50.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel50.setForeground(new java.awt.Color(0, 0, 255));
        jLabel50.setText("3. Capacity of 1000 persons");
        platinum.getContentPane().add(jLabel50);
        jLabel50.setBounds(30, 140, 250, 30);

        jLabel51.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel51.setForeground(new java.awt.Color(0, 0, 255));
        jLabel51.setText("4. Decorative Lights and Flowers");
        platinum.getContentPane().add(jLabel51);
        jLabel51.setBounds(30, 170, 300, 28);

        jLabel52.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel52.setForeground(new java.awt.Color(0, 0, 255));
        jLabel52.setText("5. Dinner facilities both veg. and non veg.");
        platinum.getContentPane().add(jLabel52);
        jLabel52.setBounds(30, 200, 370, 28);

        jLabel53.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel53.setForeground(new java.awt.Color(0, 0, 255));
        jLabel53.setText("6. Timing: 4:00pm- 10:00pm");
        platinum.getContentPane().add(jLabel53);
        jLabel53.setBounds(30, 230, 260, 30);

        jLabel54.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel54.setForeground(new java.awt.Color(0, 0, 255));
        jLabel54.setText("7. Total Charges Rs 10lac ");
        platinum.getContentPane().add(jLabel54);
        jLabel54.setBounds(30, 260, 240, 30);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (11).jpg"))); // NOI18N
        platinum.getContentPane().add(jLabel69);
        jLabel69.setBounds(0, 0, 530, 310);

        silver.setTitle("Silver Package");
        silver.setMinimumSize(new java.awt.Dimension(530, 310));
        silver.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                silverWindowActivated(evt);
            }
        });
        silver.getContentPane().setLayout(null);

        jLabel55.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel55.setForeground(new java.awt.Color(255, 0, 255));
        jLabel55.setText("Silver Package Information");
        silver.getContentPane().add(jLabel55);
        jLabel55.setBounds(100, 30, 350, 41);

        jLabel56.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel56.setForeground(new java.awt.Color(0, 0, 255));
        jLabel56.setText("1. Airconditioned");
        silver.getContentPane().add(jLabel56);
        jLabel56.setBounds(40, 90, 149, 28);

        jLabel57.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel57.setForeground(new java.awt.Color(0, 0, 255));
        jLabel57.setText("2. Capacity of 200 persons ");
        silver.getContentPane().add(jLabel57);
        jLabel57.setBounds(40, 120, 230, 28);

        jLabel58.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel58.setForeground(new java.awt.Color(0, 0, 255));
        jLabel58.setText("3. Decorative Lights and Flowers ");
        silver.getContentPane().add(jLabel58);
        jLabel58.setBounds(40, 150, 293, 28);

        jLabel59.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel59.setForeground(new java.awt.Color(0, 0, 255));
        jLabel59.setText("4. Drinks and Ice Cream ");
        silver.getContentPane().add(jLabel59);
        jLabel59.setBounds(40, 180, 210, 28);

        jLabel60.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel60.setForeground(new java.awt.Color(0, 0, 255));
        jLabel60.setText("5. Timings: 6:00pm- 9:00pm ");
        silver.getContentPane().add(jLabel60);
        jLabel60.setBounds(40, 210, 247, 28);

        jLabel61.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel61.setForeground(new java.awt.Color(0, 0, 255));
        jLabel61.setText("6. Total Charges Rs 1Lac");
        silver.getContentPane().add(jLabel61);
        jLabel61.setBounds(40, 240, 213, 28);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (11).jpg"))); // NOI18N
        jLabel70.setMaximumSize(new java.awt.Dimension(530, 340));
        jLabel70.setMinimumSize(new java.awt.Dimension(530, 340));
        silver.getContentPane().add(jLabel70);
        jLabel70.setBounds(0, 0, 530, 310);

        gold.setTitle("Gold Package");
        gold.setMinimumSize(new java.awt.Dimension(530, 310));
        gold.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                goldWindowActivated(evt);
            }
        });
        gold.getContentPane().setLayout(null);

        jLabel62.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel62.setForeground(new java.awt.Color(255, 0, 255));
        jLabel62.setText("Gold Package Information");
        gold.getContentPane().add(jLabel62);
        jLabel62.setBounds(110, 20, 337, 41);

        jLabel63.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel63.setForeground(new java.awt.Color(0, 0, 255));
        jLabel63.setText("1. Airconditioned");
        gold.getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 80, 149, 28);

        jLabel64.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel64.setForeground(new java.awt.Color(0, 0, 255));
        jLabel64.setText("2. Capacity of 500 persons");
        gold.getContentPane().add(jLabel64);
        jLabel64.setBounds(20, 110, 225, 28);

        jLabel65.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel65.setForeground(new java.awt.Color(0, 0, 255));
        jLabel65.setText("3. Decorative Lights and Flowers ");
        gold.getContentPane().add(jLabel65);
        jLabel65.setBounds(20, 140, 293, 28);

        jLabel66.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel66.setForeground(new java.awt.Color(0, 0, 255));
        jLabel66.setText("4. Dinner Facilities Both veg. and non veg. ");
        gold.getContentPane().add(jLabel66);
        jLabel66.setBounds(20, 170, 371, 28);

        jLabel67.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel67.setForeground(new java.awt.Color(0, 0, 255));
        jLabel67.setText("5. Timing: 5:00pm- 9:00pm");
        gold.getContentPane().add(jLabel67);
        jLabel67.setBounds(20, 200, 234, 28);

        jLabel68.setFont(new java.awt.Font("Monotype Corsiva", 0, 24));
        jLabel68.setForeground(new java.awt.Color(0, 0, 255));
        jLabel68.setText("6. Total Charges Rs. 5Lac ");
        gold.getContentPane().add(jLabel68);
        jLabel68.setBounds(20, 230, 223, 28);

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (11).jpg"))); // NOI18N
        jLabel71.setPreferredSize(new java.awt.Dimension(530, 340));
        gold.getContentPane().add(jLabel71);
        jLabel71.setBounds(0, 0, 530, 310);

        Custom.setTitle("Custom Package");
        Custom.setMinimumSize(new java.awt.Dimension(630, 480));
        Custom.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                CustomWindowActivated(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("Select Custom Package");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel27.setText("Time of party:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel28.setText("Food:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel29.setText("Capacity of Persons:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel30.setText("Decoration Type:");

        Charge.setFont(new java.awt.Font("Tahoma", 0, 18));
        Charge.setText("Charge:");
        Charge.setOpaque(false);
        Charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeActionPerformed(evt);
            }
        });

        ac.setFont(new java.awt.Font("Tahoma", 0, 18));
        ac.setText("Air Conditioned");
        ac.setOpaque(false);

        m.setFont(new java.awt.Font("Tahoma", 0, 18));
        m.setText("Music");
        m.setOpaque(false);

        d.setFont(new java.awt.Font("Tahoma", 0, 18));
        d.setText("Drinks");
        d.setOpaque(false);

        food.setFont(new java.awt.Font("Tahoma", 0, 18));
        food.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vegetarian only", "Non-Vegetarian only", "Both vegetarian and non-vegetarian", " " }));
        food.setOpaque(false);

        buttonGroup1.add(a);
        a.setFont(new java.awt.Font("Tahoma", 0, 18));
        a.setText("A");
        a.setOpaque(false);

        buttonGroup1.add(b);
        b.setFont(new java.awt.Font("Tahoma", 0, 18));
        b.setText("B");
        b.setOpaque(false);

        buttonGroup1.add(cd);
        cd.setFont(new java.awt.Font("Tahoma", 0, 18));
        cd.setText("C");
        cd.setOpaque(false);

        charge.setBackground(java.awt.Color.white);
        charge.setFont(new java.awt.Font("Tahoma", 0, 18));

        caop.setFont(new java.awt.Font("Tahoma", 0, 18));
        caop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                caopFocusLost(evt);
            }
        });
        caop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caopKeyTyped(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel33.setText("to");

        CustReg.setFont(new java.awt.Font("Tahoma", 0, 18));
        CustReg.setText("Register");
        CustReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustRegActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (16).jpg"))); // NOI18N
        jLabel25.setMinimumSize(new java.awt.Dimension(630, 480));

        javax.swing.GroupLayout CustomLayout = new javax.swing.GroupLayout(Custom.getContentPane());
        Custom.getContentPane().setLayout(CustomLayout);
        CustomLayout.setHorizontalGroup(
            CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m)
                    .addComponent(d)))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel27)
                .addGap(17, 17, 17)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel33)
                .addGap(4, 4, 4)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(caop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30)
                .addGap(15, 15, 15)
                .addComponent(a)
                .addGap(53, 53, 53)
                .addComponent(b)
                .addGap(53, 53, 53)
                .addComponent(cd))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(CustReg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Charge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel29))
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CustomLayout.setVerticalGroup(
            CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m)
                    .addGroup(CustomLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(d)))
                .addGap(19, 19, 19)
                .addGroup(CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(caop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(CustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(b)
                    .addComponent(cd))
                .addGap(9, 9, 9)
                .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(CustReg))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(Charge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel29))
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(CustomLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(a))
        );

        Form.setTitle("Registration Form");
        Form.setMinimumSize(new java.awt.Dimension(650, 480));
        Form.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                FormWindowActivated(evt);
            }
        });
        Form.getContentPane().setLayout(null);

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("Registration Form");
        Form.getContentPane().add(jLabel31);
        jLabel31.setBounds(210, 10, 250, 40);

        jLabel32.setDisplayedMnemonic('N');
        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel32.setLabelFor(Name);
        jLabel32.setText("Name*");
        Form.getContentPane().add(jLabel32);
        jLabel32.setBounds(50, 90, 55, 22);

        jLabel34.setDisplayedMnemonic('A');
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel34.setLabelFor(add);
        jLabel34.setText("Address*");
        Form.getContentPane().add(jLabel34);
        jLabel34.setBounds(50, 120, 72, 22);

        jLabel35.setDisplayedMnemonic('P');
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel35.setLabelFor(fon);
        jLabel35.setText("Phone No.");
        Form.getContentPane().add(jLabel35);
        jLabel35.setBounds(50, 150, 82, 22);

        jLabel36.setDisplayedMnemonic('M');
        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel36.setLabelFor(mobile);
        jLabel36.setText("Mobile No.*");
        Form.getContentPane().add(jLabel36);
        jLabel36.setBounds(50, 180, 94, 22);

        jLabel37.setDisplayedMnemonic('B');
        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel37.setLabelFor(bpn);
        jLabel37.setText("Birthday's Person Name");
        Form.getContentPane().add(jLabel37);
        jLabel37.setBounds(50, 210, 187, 22);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel38.setText("No. of Persons");
        Form.getContentPane().add(jLabel38);
        jLabel38.setBounds(50, 240, 116, 22);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel39.setText("Total Charges Rs.");
        Form.getContentPane().add(jLabel39);
        jLabel39.setBounds(50, 270, 139, 22);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel40.setText("Advance Charge Rs.");
        Form.getContentPane().add(jLabel40);
        jLabel40.setBounds(50, 300, 157, 22);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel41.setText("Balance Charges Rs.");
        Form.getContentPane().add(jLabel41);
        jLabel41.setBounds(50, 330, 159, 22);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel43.setForeground(new java.awt.Color(0, 0, 204));
        jLabel43.setText("*Fields Are Compulsory");
        Form.getContentPane().add(jLabel43);
        jLabel43.setBounds(50, 360, 150, 17);

        Name.setFont(new java.awt.Font("Tahoma", 0, 18));
        Name.setNextFocusableComponent(add);
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        Form.getContentPane().add(Name);
        Name.setBounds(240, 90, 190, 28);

        add.setFont(new java.awt.Font("Tahoma", 0, 18));
        add.setNextFocusableComponent(fon);
        Form.getContentPane().add(add);
        add.setBounds(240, 120, 190, 28);

        fon.setFont(new java.awt.Font("Tahoma", 0, 18));
        fon.setNextFocusableComponent(mobile);
        fon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fonFocusLost(evt);
            }
        });
        fon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fonKeyTyped(evt);
            }
        });
        Form.getContentPane().add(fon);
        fon.setBounds(240, 150, 190, 28);

        mobile.setFont(new java.awt.Font("Tahoma", 0, 18));
        mobile.setNextFocusableComponent(bpn);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileFocusLost(evt);
            }
        });
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        Form.getContentPane().add(mobile);
        mobile.setBounds(240, 180, 190, 28);

        bpn.setFont(new java.awt.Font("Tahoma", 0, 18));
        bpn.setNextFocusableComponent(M);
        bpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bpnKeyTyped(evt);
            }
        });
        Form.getContentPane().add(bpn);
        bpn.setBounds(240, 210, 190, 28);

        tc.setBackground(new java.awt.Color(255, 255, 255));
        tc.setFont(new java.awt.Font("Tahoma", 0, 18));
        Form.getContentPane().add(tc);
        tc.setBounds(240, 270, 190, 30);

        adc.setBackground(new java.awt.Color(255, 255, 255));
        adc.setFont(new java.awt.Font("Tahoma", 0, 18));
        Form.getContentPane().add(adc);
        adc.setBounds(240, 300, 190, 30);

        bc.setBackground(new java.awt.Color(255, 255, 255));
        bc.setFont(new java.awt.Font("Tahoma", 0, 18));
        Form.getContentPane().add(bc);
        bc.setBounds(240, 330, 190, 30);

        packe.setFont(new java.awt.Font("Curlz MT", 1, 30));
        packe.setForeground(new java.awt.Color(51, 255, 51));
        Form.getContentPane().add(packe);
        packe.setBounds(490, 0, 160, 60);

        RegBTN.setBackground(new java.awt.Color(255, 255, 255));
        RegBTN.setFont(new java.awt.Font("Tahoma", 0, 18));
        RegBTN.setForeground(new java.awt.Color(51, 51, 255));
        RegBTN.setText("Register");
        RegBTN.setNextFocusableComponent(Back);
        RegBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegBTNActionPerformed(evt);
            }
        });
        Form.getContentPane().add(RegBTN);
        RegBTN.setBounds(480, 150, 140, 30);

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18));
        Back.setForeground(new java.awt.Color(0, 51, 255));
        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Form.getContentPane().add(Back);
        Back.setBounds(480, 210, 140, 31);

        CanEvnt.setFont(new java.awt.Font("Tahoma", 0, 18));
        CanEvnt.setForeground(new java.awt.Color(0, 51, 204));
        CanEvnt.setText("Cancel Event");
        CanEvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanEvntActionPerformed(evt);
            }
        });
        Form.getContentPane().add(CanEvnt);
        CanEvnt.setBounds(480, 270, 140, 30);

        dat.setFont(new java.awt.Font("Tahoma", 0, 18));
        dat.setForeground(new java.awt.Color(255, 255, 0));
        Form.getContentPane().add(dat);
        dat.setBounds(200, 50, 300, 30);

        noope.setFont(new java.awt.Font("Tahoma", 0, 18));
        Form.getContentPane().add(noope);
        noope.setBounds(240, 240, 190, 30);

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel72.setText("Gender:");
        Form.getContentPane().add(jLabel72);
        jLabel72.setBounds(470, 100, 70, 20);

        buttonGroup2.add(M);
        M.setFont(new java.awt.Font("Tahoma", 0, 18));
        M.setText("M");
        M.setNextFocusableComponent(RegBTN);
        M.setOpaque(false);
        Form.getContentPane().add(M);
        M.setBounds(540, 100, 40, 20);

        buttonGroup2.add(F);
        F.setFont(new java.awt.Font("Tahoma", 0, 18));
        F.setText("F");
        F.setOpaque(false);
        Form.getContentPane().add(F);
        F.setBounds(580, 100, 35, 20);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background_LEY.jpg"))); // NOI18N
        jLabel47.setMinimumSize(new java.awt.Dimension(641, 465));
        Form.getContentPane().add(jLabel47);
        jLabel47.setBounds(0, 0, 660, 440);

        jLabel42.setText("jLabel42");
        Form.getContentPane().add(jLabel42);
        jLabel42.setBounds(590, 390, 40, 14);

        jOptionPane1.setMessageType(1);

        jOptionPane2.setMessageType(1);

        checkSTS.setTitle("Select Serial No.");
        checkSTS.setMinimumSize(new java.awt.Dimension(460, 250));
        checkSTS.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                checkSTSWindowActivated(evt);
            }
        });
        checkSTS.getContentPane().setLayout(null);

        jLabel44.setFont(new java.awt.Font("Chiller", 1, 36));
        jLabel44.setForeground(new java.awt.Color(255, 0, 204));
        jLabel44.setText("Select Your Serial Number ");
        checkSTS.getContentPane().add(jLabel44);
        jLabel44.setBounds(70, 20, 335, 42);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel45.setForeground(new java.awt.Color(255, 0, 255));
        jLabel45.setText("Serial No.");
        checkSTS.getContentPane().add(jLabel45);
        jLabel45.setBounds(150, 80, 75, 22);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18));
        checkSTS.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 80, 39, 20);

        Next.setFont(new java.awt.Font("Tahoma", 0, 18));
        Next.setForeground(new java.awt.Color(255, 0, 255));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        checkSTS.getContentPane().add(Next);
        Next.setBounds(180, 150, 80, 30);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (10).jpg"))); // NOI18N
        checkSTS.getContentPane().add(jLabel46);
        jLabel46.setBounds(0, 0, 460, 210);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setMinimumSize(new java.awt.Dimension(650, 465));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 44));
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Event Management System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 610, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Programmed And Presented By");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 70, 340, 40);

        jLabel4.setFont(new java.awt.Font("Castellar", 0, 24));
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("CHIRAG GARG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 120, 200, 29);

        Welcome.setFont(new java.awt.Font("Tahoma", 0, 24));
        Welcome.setForeground(new java.awt.Color(0, 153, 51));
        Welcome.setText("ENTER");
        Welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeActionPerformed(evt);
            }
        });
        getContentPane().add(Welcome);
        Welcome.setBounds(250, 260, 110, 30);

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 48));
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("WELCOME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 180, 260, 60);

        jLabel73.setFont(new java.awt.Font("Brush Script MT", 0, 42));
        jLabel73.setText("This software is programmed in Java");
        getContentPane().add(jLabel73);
        jLabel73.setBounds(30, 370, 580, 60);

        Wel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavens-farm-hd-wallpaper-desk.jpg"))); // NOI18N
        Wel.setOpaque(true);
        getContentPane().add(Wel);
        Wel.setBounds(0, 0, 630, 450);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-641)/2, (screenSize.height-487)/2, 641, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void WelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeActionPerformed
id.setVisible(true);
dispose();
// TODO add your handling code here:
}//GEN-LAST:event_WelcomeActionPerformed

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
String loginid = LoginTF.getText();
String pwd = new String(Pwdpf.getPassword());
String str = null;
        Statement stmt=null;
        ResultSet rs = null;
        try
        {

            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Event_Management_System";
            Connection conn = DriverManager.getConnection(database, "root", "chirag");
            stmt = conn.createStatement();
            String sql = "select * from Login where ID = '"+loginid+"'";
            rs = stmt.executeQuery(sql);
            rs.next();
            str = rs.getString("Password");
            stmt.close();
            conn.close();
            if(str.equals(pwd))
{
  Sel.setVisible(true);
  id.dispose();
}
else
{
         Alr.setText("Incorrect ID or Password");
         msg.setVisible(true);
         Pwdpf.setBackground(Color.YELLOW);
         }
} catch (Exception e) { JOptionPane.showMessageDialog(null,"Incorrect ID or Password" );}
// TODO add your handling code here:
}//GEN-LAST:event_SigninActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String txt = Alr.getText();
if(txt.equals("Incorrect ID or Password")){
    msg.dispose();}// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
System.exit(0);    // TODO add your handling code here:
}//GEN-LAST:event_jMenu1ActionPerformed

private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
   // TODO add your handling code here:
}//GEN-LAST:event_jMenu2ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
   About.setVisible(true);
  // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenu1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu1AncestorAdded
    // TODO add your handling code here:
}//GEN-LAST:event_jMenu1AncestorAdded

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
System.exit(0);    // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void CustPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustPackActionPerformed
Custom.setVisible(true);
birthdayevent.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_CustPackActionPerformed
int c;
Double ad = 0.0 , ba = 0.0;
Double chrg = 0.0;
private void ChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeActionPerformed
String cop ;
cop =  caop.getText();
if(caop.getText().equals("") == true){
   JOptionPane.showMessageDialog(null, "Please enter number of persons");
}else{
int chrge ;
c = Integer.parseInt(caop.getText());
String fud = (String)food.getSelectedItem();
Double i=0.0;
if(ac.isSelected() == true)
    i = 30000.0;
if(m.isSelected() == true)
    i = i + 10000.0;
if(d.isSelected()== true)
    i = i + 3000.0;
if(a.isSelected() == true)
    i = i + 10000.0;
if(b.isSelected() == true)
    i = i + 20000.0;
if(cd.isSelected()== true)
    i = i + 30000.0;
String f = (String)food.getSelectedItem();
Double  j=0.0;
if(fud.equals("Both vegetarian and non-vegetarian"))
    j =  600.0;
else if(fud.equals("Vegetarian only"))
    j = 300.0;
else if(fud.equals("Non-vegetarian only"))
    j = 400.0;
chrg = c*j + i ;
charge.setText("Rs."+ chrg);
ad = 0.5*chrg;
ba = 0.5*chrg;
}// TODO add your handling code here:
}//GEN-LAST:event_ChargeActionPerformed

private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
CanEvnt.setEnabled(true);
RegBTN.setEnabled(true);
birthdayevent.setVisible(true);
Form.dispose();
Name.setText("");
add.setText("");
fon.setText("");
mobile.setText("");
bpn.setText("");
tc.setText("");
bc.setText("");
noope.setText("");
adc.setText("");// TODO add your handling code here:
}//GEN-LAST:event_BackActionPerformed

private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_mobileActionPerformed

private void DateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateBTNActionPerformed
        java.util.Date dt = jDateChooser1.getDate();

dat.setText(""+ dt);
    Form.setVisible(true);
   CanEvnt.setEnabled(false);
Date.dispose();// TODO add your handling code here:
}//GEN-LAST:event_DateBTNActionPerformed

private void CustRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustRegActionPerformed
String cop ;
cop =  caop.getText();
if(caop.getText().equals("") == true){
    JOptionPane.showMessageDialog(null, "Please enter number of persons");
}else{
int chrge ;
Date.setVisible(true);
c = Integer.parseInt(caop.getText());
String fud = (String)food.getSelectedItem();
Double i=0.0;
if(ac.isSelected() == true)
    i = 30000.0;
if(m.isSelected() == true)
    i = i + 10000.0;
if(d.isSelected()== true)
    i = i + 3000.0;
if(a.isSelected() == true)
    i = i + 10000.0;
if(b.isSelected() == true)
    i = i + 20000.0;
if(cd.isSelected()== true)
    i = i + 30000.0;
String f = (String)food.getSelectedItem();
Double  j=0.0;
if(fud.equals("Both vegetarian and non-vegetarian"))
    j =  600.0;
else if(fud.equals("Vegetarian only"))
    j = 300.0;
else if(fud.equals("Non-vegetarian only"))
    j = 400.0;
chrg = c*j + i ;
charge.setText("Rs."+ chrg);
ad = 0.5*chrg;
ba = 0.5*chrg;
noope.setText("" + cop);
tc.setText(chrg + "");
bc.setText("" + ba);
adc.setText("" + ad);
packe.setText("Custom");
Custom.dispose();
 }// TODO add your handling code here:
}//GEN-LAST:event_CustRegActionPerformed

private void RegBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegBTNActionPerformed
char gender = 'n';
if(M.isSelected()){
    gender = 'M';
}
else{
   gender = 'F';
}
java.util.Date dt = jDateChooser1.getDate();
        int sno=0;
try{
    Class.forName("java.sql.Driver");
 String database = "jdbc:mysql://localhost:3306/Event_Management_System";
 Connection conn = DriverManager.getConnection(database, "root", "chirag");
 Statement stmt = conn.createStatement();
 String sql2 = "SELECT max(SNo) FROM Customer";
 ResultSet rs = stmt.executeQuery(sql2);
 rs.next();
 sno = rs.getInt(1)+1;
 String sql = "INSERT INTO Customer VALUES ( '" + Name.getText() + "', '" + add.getText() + "','" + fon.getText() + "', ' "+ mobile.getText() +" ','" + bpn.getText()+ "', "+ sno +" , '"+ gender + "', '"+ dt +"' , '"+ noope.getText() +"' , '"+ tc.getText() +"' , '"+ adc.getText() +"' , '"+ bc.getText() +"' , '"+ packe.getText() +"');";
 stmt.executeUpdate(sql);
 stmt.close();
 conn.close();
        RegBTN.setEnabled(false);
}
catch( Exception e)
{JOptionPane.showMessageDialog(null,"Please enter the required fields");}
        if(Name.getText().equals("") == true)
    JOptionPane.showMessageDialog(null, "Please enter the name");
    else
        if(add.getText().equals("") == true)
    JOptionPane.showMessageDialog(null, "Please enter the address");
    else
        if(mobile.getText().equals("") == true)
    JOptionPane.showMessageDialog(null, "Please enter the mobile no.");
        else
            JOptionPane.showMessageDialog(null, "Registration Successful!!\n Your serial number is " + sno );

// TODO add your handling code here:
}//GEN-LAST:event_RegBTNActionPerformed

private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu3ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
  Sel.setVisible(true);
birthdayevent.dispose();  // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
id.setVisible(true);
birthdayevent.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    Wel.setVisible(true);
birthdayevent.dispose(); // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
About.setVisible(true);    // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void plMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseClicked
Date.setVisible(true);
birthdayevent.dispose();
noope.setText("1000");
tc.setText("10Lac");
bc.setText("5Lac");
adc.setText("5LAC");
packe.setText("Platinum");    // TODO add your handling code here:
}//GEN-LAST:event_plMouseClicked

private void golMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golMouseClicked
birthdayevent.dispose();
    Date.setVisible(true);
noope.setText("500");
tc.setText("5Lac");
bc.setText("2.5Lac");
adc.setText("2.5LAC");
packe.setText("Golden");    // TODO add your handling code here:
}//GEN-LAST:event_golMouseClicked

private void silMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silMouseClicked
birthdayevent.dispose();
    Date.setVisible(true) ;
noope.setText("200");
tc.setText("1Lac");
bc.setText("0.5Lac");
adc.setText("0.5LAC");
packe.setText("Silver");    // TODO add your handling code here:
}//GEN-LAST:event_silMouseClicked

private void BirthLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BirthLabelMouseClicked
File f = new File("C:\\Users\\DARSHITA\\Documents\\NetBeansProjects\\Sound\\src\\01Happy_Birthday (1).wav");
try{ URL url = f.toURI().toURL();
Applet.newAudioClip(url).play();}
catch (Exception e){JOptionPane.showMessageDialog(null,e);}
birthdayevent.setVisible(true);
Sel.dispose();    // TODO add your handling code here:
}//GEN-LAST:event_BirthLabelMouseClicked

private void CanEvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanEvntActionPerformed
    int can = JOptionPane.showConfirmDialog(null, "Wanna delete the event for sure?");
if(can == JOptionPane.YES_OPTION){
    try{
         Class.forName("java.sql.Driver");
 String database = "jdbc:mysql://localhost:3306/Event_Management_System";
 Connection conn = DriverManager.getConnection(database, "root", "chirag");
    Statement    stmt = conn.createStatement();
        String sql = "Delete From Customer Where Sno = "+jLabel43.getText()+ ";";// TODO add your handling code here:
stmt.executeUpdate(sql);
JOptionPane.showMessageDialog(null, "Record Deleted!");
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "" + e);
    }
           }
Name.setText("");
add.setText("");
fon.setText("");
mobile.setText("");
bpn.setText("");
tc.setText("");
bc.setText("");
noope.setText("");
adc.setText("");
CanEvnt.setEnabled(false);
RegBTN.setEnabled(false);
}//GEN-LAST:event_CanEvntActionPerformed

private void PlatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatDetailActionPerformed
platinum.setVisible(true);    // TODO add your handling code here:
}//GEN-LAST:event_PlatDetailActionPerformed

private void GoldDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldDetailActionPerformed
gold.setVisible(true);    // TODO add your handling code here:
}//GEN-LAST:event_GoldDetailActionPerformed

private void SilDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilDetailActionPerformed
silver.setVisible(true);    // TODO add your handling code here:
}//GEN-LAST:event_SilDetailActionPerformed

private void CheckSTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSTSActionPerformed
checkSTS.setVisible(true);
 try{
    Class.forName("java.sql.Driver");
 String database = "jdbc:mysql://localhost:3306/Event_Management_System";
 Connection conn = DriverManager.getConnection(database, "root", "chirag");
 Statement stmt = conn.createStatement();
 String sql3 = "Select Sno From Customer;";
ResultSet rs =  stmt.executeQuery(sql3);
String sql4 = "Select max(Sno) From Customer;";
rs.next();
int rssno = rs.getInt(1);
ResultSet rs1 = stmt.executeQuery(sql4);
rs1.next();
int maxsno = rs1.getInt(1);
for(int i = rssno; i<=maxsno; i++){
    jComboBox1.addItem(i);
}
    }
catch(Exception e)
{JOptionPane.showMessageDialog(null,""+ e);
}// TODO add your handling code here:
}//GEN-LAST:event_CheckSTSActionPerformed

private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        Form.setVisible(true);
checkSTS.dispose();
birthdayevent.dispose();
Integer ss = (Integer)jComboBox1.getSelectedItem();
try{
    Class.forName("java.sql.Driver");
 String database = "jdbc:mysql://localhost:3306/Event_Management_System";
 Connection conn = DriverManager.getConnection(database, "root", "chirag");
 Statement stmt = conn.createStatement();
 String sql3 = "Select * From Customer Where Sno = "+ss+";";
ResultSet rs =  stmt.executeQuery(sql3);
rs.next();
Name.setText(rs.getString(1));
 add.setText(rs.getString(2));
 fon.setText(rs.getString(3));
 mobile.setText(rs.getString(4));
 bpn.setText(rs.getString(5));
 dat.setText(rs.getString(8));
  noope.setText(rs.getString(9));
   tc.setText(rs.getString(10));
    adc.setText(rs.getString(11));
     bc.setText(rs.getString(12));
     packe.setText(rs.getString(13));
String gen = rs.getString(7);
if(gen.equals("M") )
    M.setSelected(true);
else
     F.setSelected(true);
 stmt.close();
conn.close();
    }
catch(Exception e)
{JOptionPane.showMessageDialog(null,""+ e);
}jComboBox1.removeAllItems();// TODO add your handling code here:
RegBTN.setEnabled(false);
CanEvnt.setEnabled(true);
jLabel43.setText("" + ss);
}//GEN-LAST:event_NextActionPerformed

private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
char ch = evt.getKeyChar();
if(!( (ch>='a' && ch<+'z')|| ch == KeyEvent.VK_BACK_SPACE || ch == KeyEvent.VK_DELETE || ch == KeyEvent.VK_SPACE || ch == KeyEvent.VK_SHIFT))
    evt.consume();// TODO add your handling code here:
}//GEN-LAST:event_NameKeyTyped
private void bpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpnKeyTyped
   char ch = evt.getKeyChar();
if(!( (ch>='a' && ch<+'z')|| ch == KeyEvent.VK_BACK_SPACE || ch == KeyEvent.VK_DELETE || ch == KeyEvent.VK_SPACE || ch == KeyEvent.VK_SHIFT ))
    evt.consume(); // TODO add your handling code here:
}//GEN-LAST:event_bpnKeyTyped

private void fonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fonFocusLost
int fone = Integer.parseInt(fon.getText());
if(fone <= 0)
    JOptionPane.showMessageDialog(null, "Phone No. cannot be <= 0");// TODO add your handling code here:
}//GEN-LAST:event_fonFocusLost

private void mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusLost
int mobileno = Integer.parseInt(mobile.getText());
if(mobileno <= 0)
    JOptionPane.showMessageDialog(null, "Mobile No. cannot be <= 0");
// TODO add your handling code here:
}//GEN-LAST:event_mobileFocusLost

private void caopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caopFocusLost
int cop = Integer.parseInt(caop.getText());
if(cop <= 0)
    JOptionPane.showMessageDialog(null, "Capacity cannot be <= 0");    // TODO add your handling code here:
}//GEN-LAST:event_caopFocusLost

private void caopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caopKeyTyped
char ch = evt.getKeyChar();
if(! (ch >= '0' && ch <='9'))
    evt.consume();    // TODO add your handling code here:
}//GEN-LAST:event_caopKeyTyped

private void fonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fonKeyTyped
char ch = evt.getKeyChar();
if(! (ch >= '0' && ch <='9'))
    evt.consume();    // TODO add your handling code here:
}//GEN-LAST:event_fonKeyTyped

private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
char ch = evt.getKeyChar();
if(! (ch >= '0' && ch <='9'))
    evt.consume();    // TODO add your handling code here:
}//GEN-LAST:event_mobileKeyTyped

private void idWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_idWindowActivated
id.setLocationRelativeTo(null);
// TODO add your handling code here:
}//GEN-LAST:event_idWindowActivated

private void SelWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SelWindowActivated
Sel.setLocationRelativeTo(null);    
}//GEN-LAST:event_SelWindowActivated

private void msgWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_msgWindowActivated
msg.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_msgWindowActivated

private void AboutWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AboutWindowActivated
About.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_AboutWindowActivated

private void birthdayeventWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_birthdayeventWindowActivated
birthdayevent.setLocationRelativeTo(null);
// TODO add your handling code here:
}//GEN-LAST:event_birthdayeventWindowActivated

private void DateWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DateWindowActivated
Date.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_DateWindowActivated

private void platinumWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_platinumWindowActivated
platinum.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_platinumWindowActivated

private void silverWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_silverWindowActivated
silver.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_silverWindowActivated

private void goldWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_goldWindowActivated
gold.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_goldWindowActivated

private void CustomWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CustomWindowActivated
Custom.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_CustomWindowActivated

private void FormWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FormWindowActivated
Form.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_FormWindowActivated

private void checkSTSWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_checkSTSWindowActivated
checkSTS.setLocationRelativeTo(null);    // TODO add your handling code here:
}//GEN-LAST:event_checkSTSWindowActivated

private void BirthLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BirthLabelMouseEntered
Sel.setCursor(Cursor.HAND_CURSOR);
BirthLabel.setForeground(Color.BLUE) ;    // TODO add your handling code here:
}//GEN-LAST:event_BirthLabelMouseEntered

private void BirthLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BirthLabelMouseExited
BirthLabel.setForeground(new java.awt.Color(255, 0, 204)) ;
Sel.setCursor(Cursor.DEFAULT_CURSOR);// TODO add your handling code here:
}//GEN-LAST:event_BirthLabelMouseExited

private void plMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseEntered
birthdayevent.setCursor(Cursor.HAND_CURSOR);
pl.setForeground(Color.BLUE) ;  // TODO add your handling code here:
}//GEN-LAST:event_plMouseEntered

private void plMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseExited
birthdayevent.setCursor(Cursor.DEFAULT_CURSOR);
pl.setForeground(new java.awt.Color(204, 0, 204)) ;    // TODO add your handling code here:
}//GEN-LAST:event_plMouseExited

private void golMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golMouseEntered
birthdayevent.setCursor(Cursor.HAND_CURSOR);
gol.setForeground(Color.BLUE) ; // TODO add your handling code here:
}//GEN-LAST:event_golMouseEntered

private void golMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golMouseExited
birthdayevent.setCursor(Cursor.DEFAULT_CURSOR);
gol.setForeground(new java.awt.Color(204, 0, 204)) ;  // TODO add your handling code here:
}//GEN-LAST:event_golMouseExited

private void silMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silMouseExited
birthdayevent.setCursor(Cursor.DEFAULT_CURSOR);
sil.setForeground(new java.awt.Color(204, 0, 204)) ;    // TODO add your handling code here:
}//GEN-LAST:event_silMouseExited

private void silMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silMouseEntered
birthdayevent.setCursor(Cursor.HAND_CURSOR);
sil.setForeground(Color.BLUE) ;  // TODO add your handling code here:

}//GEN-LAST:event_silMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog About;
    private javax.swing.JLabel Alr;
    private javax.swing.JButton Back;
    private javax.swing.JLabel BirthLabel;
    private javax.swing.JButton CanEvnt;
    private javax.swing.JButton Charge;
    private javax.swing.JButton CheckSTS;
    private javax.swing.JButton CustPack;
    private javax.swing.JButton CustReg;
    private javax.swing.JFrame Custom;
    private javax.swing.JFrame Date;
    private javax.swing.JButton DateBTN;
    private javax.swing.JRadioButton F;
    private javax.swing.JFrame Form;
    private javax.swing.JButton GoldDetail;
    private javax.swing.JTextField LoginTF;
    private javax.swing.JRadioButton M;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Next;
    private javax.swing.JButton PlatDetail;
    private javax.swing.JPasswordField Pwdpf;
    private javax.swing.JButton RegBTN;
    private javax.swing.JFrame Sel;
    private javax.swing.JButton Signin;
    private javax.swing.JButton SilDetail;
    private javax.swing.JLabel Wel;
    private javax.swing.JButton Welcome;
    private javax.swing.JRadioButton a;
    private javax.swing.JCheckBox ac;
    private javax.swing.JLabel adc;
    private javax.swing.JTextField add;
    private javax.swing.JRadioButton b;
    private javax.swing.JLabel bc;
    private javax.swing.JFrame birthdayevent;
    private javax.swing.JTextField bpn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField caop;
    private javax.swing.JRadioButton cd;
    private javax.swing.JLabel charge;
    private javax.swing.JFrame checkSTS;
    private javax.swing.JCheckBox d;
    private javax.swing.JLabel dat;
    private javax.swing.JTextField fon;
    private javax.swing.JComboBox food;
    private javax.swing.JLabel gol;
    private javax.swing.JDialog gold;
    private javax.swing.JFrame id;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JCheckBox m;
    private javax.swing.JTextField mobile;
    private javax.swing.JDialog msg;
    private javax.swing.JLabel noope;
    private javax.swing.JLabel packe;
    private javax.swing.JLabel pl;
    private javax.swing.JDialog platinum;
    private javax.swing.JLabel sil;
    private javax.swing.JDialog silver;
    private javax.swing.JLabel tc;
    // End of variables declaration//GEN-END:variables

}
